extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest
env:
  node: true
ignorePatterns:
  - dist
overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: tsconfig.json
    rules:
     #This can be investigated in the future, since there are two files whose filenames doesn't match the exported ones
     "filenames/match-exported": off

